# _Dask_ arrays and parallel calculation

Now, let's create a function that calculates the e-folding time. First, we define this function with NumPy syntax.

```python
def efold_numpy(array):
    ecorr = np.correlate((array-np.mean(array))/np.std(array),(array-np.mean(array))
                         /np.std(array),'same')/len(array)
    lag1 = ecorr[int(len(ecorr)/2)+1]
    efold_numpy = -1/np.log(lag1)
    return efold_numpy
```

We are going to use the function ```xr.apply_ufunc``` again. However, there are two important features to consider when using Dask. 

Firstly, we have to execute parallel calculation by including ```dask="parallelized"``` and ```allow_rechunk = True``` in the function.

```python
def efold_xarray(array):
    efold_xarray = xr.apply_ufunc(
            efold_numpy, 
            t_daily.groupby('time.month'), 
            input_core_dims=[["time"]],  
            exclude_dims=set(("time",)),
            vectorize=True,  
            dask="parallelized",
            dask_gufunc_kwargs = dict(allow_rechunk = True),
            output_dtypes=[array['tasmax'].dtype]).rename({"tasmax": "efold"})
    return efold_xarray
```

Secondly, we have to define the size of our chunks when opening the NetCDF files. By specifying the chunk shape, xarray will automatically create Dask arrays for each data variable in the Dataset. 

In this case, the chunck size is defined when loading the NetCDF file with the ```xr.open_dataset``` function. Since we are calculating the variable over the time dimension, we need to specify chuncks of latitude and longitude. The chuncks are created, thus, by setting the shape an specific shape on those dimensions, ```chunks={"lat": 150, "lon": 200}```.

```python
efold_model = []

for file_name in multimodel:
        t_daily = xr.open_dataset(file_name,chunks={"lat": 150, "lon": 200})
        efold = efold_xarray(t_daily)
        efold_model.append(efold)

efold_model = xr.concat(efold_model,pd.Index(range(25),name='model'))
```

<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewBox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewBox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 20px 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: none;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2 {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class='xr-text-repr-fallback'>&lt;xarray.Dataset&gt;
Dimensions:  (month: 2, model: 25, lat: 510, lon: 1068)
Coordinates:
  * month    (month) int64 1 2
  * lat      (lat) float64 41.04 41.12 41.21 41.29 ... 83.21 83.29 83.37 83.46
  * lon      (lon) float64 -141.0 -140.9 -140.8 -140.7 ... -52.21 -52.13 -52.04
  * model    (model) int64 0 1 2 3 4 5 6 7 8 9 ... 15 16 17 18 19 20 21 22 23 24
Data variables:
    efold    (model, month, lat, lon) float32 dask.array&lt;chunksize=(1, 1, 150, 200), meta=np.ndarray&gt;</pre><div class='xr-wrap' hidden><div class='xr-header'><div class='xr-obj-type'>xarray.Dataset</div></div><ul class='xr-sections'><li class='xr-section-item'><input id='section-6cc4401e-c4db-468f-be4b-2746eb43cd31' class='xr-section-summary-in' type='checkbox' disabled ><label for='section-6cc4401e-c4db-468f-be4b-2746eb43cd31' class='xr-section-summary'  title='Expand/collapse section'>Dimensions:</label><div class='xr-section-inline-details'><ul class='xr-dim-list'><li><span class='xr-has-index'>month</span>: 2</li><li><span class='xr-has-index'>model</span>: 25</li><li><span class='xr-has-index'>lat</span>: 510</li><li><span class='xr-has-index'>lon</span>: 1068</li></ul></div><div class='xr-section-details'></div></li><li class='xr-section-item'><input id='section-75eac8a8-0d35-4c29-ba50-35e2433c92a3' class='xr-section-summary-in' type='checkbox'  checked><label for='section-75eac8a8-0d35-4c29-ba50-35e2433c92a3' class='xr-section-summary' >Coordinates: <span>(4)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>month</span></div><div class='xr-var-dims'>(month)</div><div class='xr-var-dtype'>int64</div><div class='xr-var-preview xr-preview'>1 2</div><input id='attrs-d742d1a4-c626-49e5-a8ab-0059163f3973' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-d742d1a4-c626-49e5-a8ab-0059163f3973' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-6e36e647-ae61-48f9-a8e3-cf14fc24503b' class='xr-var-data-in' type='checkbox'><label for='data-6e36e647-ae61-48f9-a8e3-cf14fc24503b' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([1, 2])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>lat</span></div><div class='xr-var-dims'>(lat)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>41.04 41.12 41.21 ... 83.37 83.46</div><input id='attrs-93cfe7b5-2e4c-4dca-9f41-bfbe7fde8e73' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-93cfe7b5-2e4c-4dca-9f41-bfbe7fde8e73' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-d1010138-3539-499f-bd70-a81d68cd91ce' class='xr-var-data-in' type='checkbox'><label for='data-d1010138-3539-499f-bd70-a81d68cd91ce' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([41.041667, 41.125   , 41.208333, ..., 83.291665, 83.374998, 83.458332])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>lon</span></div><div class='xr-var-dims'>(lon)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>-141.0 -140.9 ... -52.13 -52.04</div><input id='attrs-22ff8a65-5ee2-4de1-b933-b4a46bb00886' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-22ff8a65-5ee2-4de1-b933-b4a46bb00886' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-59b2c9da-74ed-48c9-ab28-c22d0c0616ab' class='xr-var-data-in' type='checkbox'><label for='data-59b2c9da-74ed-48c9-ab28-c22d0c0616ab' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([-140.958333, -140.875   , -140.791667, ...,  -52.208337,  -52.125004,
        -52.04167 ])</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>model</span></div><div class='xr-var-dims'>(model)</div><div class='xr-var-dtype'>int64</div><div class='xr-var-preview xr-preview'>0 1 2 3 4 5 6 ... 19 20 21 22 23 24</div><input id='attrs-4765df0d-f486-48ef-94c2-a2053e157fa1' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-4765df0d-f486-48ef-94c2-a2053e157fa1' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-4a231426-a810-43f4-9aed-2db65dd27035' class='xr-var-data-in' type='checkbox'><label for='data-4a231426-a810-43f4-9aed-2db65dd27035' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])</pre></div></li></ul></div></li><li class='xr-section-item'><input id='section-95f9575e-2047-483d-8515-1718179edad2' class='xr-section-summary-in' type='checkbox'  checked><label for='section-95f9575e-2047-483d-8515-1718179edad2' class='xr-section-summary' >Data variables: <span>(1)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-var-name'><span>efold</span></div><div class='xr-var-dims'>(model, month, lat, lon)</div><div class='xr-var-dtype'>float32</div><div class='xr-var-preview xr-preview'>dask.array&lt;chunksize=(1, 1, 150, 200), meta=np.ndarray&gt;</div><input id='attrs-3b2c44c7-1162-4e06-b5dd-3bb817562016' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-3b2c44c7-1162-4e06-b5dd-3bb817562016' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-e903b37a-a79c-4380-b7d7-9541e4bfc0fc' class='xr-var-data-in' type='checkbox'><label for='data-e903b37a-a79c-4380-b7d7-9541e4bfc0fc' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><table>
<tr>
<td>
<table>
  <thead>
    <tr><td> </td><th> Array </th><th> Chunk </th></tr>
  </thead>
  <tbody>
    <tr><th> Bytes </th><td> 103.89 MiB </td> <td> 117.19 kiB </td></tr>
    <tr><th> Shape </th><td> (25, 2, 510, 1068) </td> <td> (1, 1, 150, 200) </td></tr>
    <tr><th> Count </th><td> 9291 Tasks </td><td> 1200 Chunks </td></tr>
    <tr><th> Type </th><td> float32 </td><td> numpy.ndarray </td></tr>
  </tbody>
</table>
</td>
<td>
<svg width="382" height="122" style="stroke:rgb(0,0,0);stroke-width:1" >

  <!-- Horizontal lines -->
  <line x1="0" y1="0" x2="29" y2="0" style="stroke-width:2" />
  <line x1="0" y1="25" x2="29" y2="25" style="stroke-width:2" />

  <!-- Vertical lines -->
  <line x1="0" y1="0" x2="0" y2="25" style="stroke-width:2" />
  <line x1="1" y1="0" x2="1" y2="25" />
  <line x1="2" y1="0" x2="2" y2="25" />
  <line x1="3" y1="0" x2="3" y2="25" />
  <line x1="4" y1="0" x2="4" y2="25" />
  <line x1="5" y1="0" x2="5" y2="25" />
  <line x1="7" y1="0" x2="7" y2="25" />
  <line x1="8" y1="0" x2="8" y2="25" />
  <line x1="9" y1="0" x2="9" y2="25" />
  <line x1="10" y1="0" x2="10" y2="25" />
  <line x1="11" y1="0" x2="11" y2="25" />
  <line x1="13" y1="0" x2="13" y2="25" />
  <line x1="14" y1="0" x2="14" y2="25" />
  <line x1="15" y1="0" x2="15" y2="25" />
  <line x1="16" y1="0" x2="16" y2="25" />
  <line x1="17" y1="0" x2="17" y2="25" />
  <line x1="19" y1="0" x2="19" y2="25" />
  <line x1="20" y1="0" x2="20" y2="25" />
  <line x1="21" y1="0" x2="21" y2="25" />
  <line x1="22" y1="0" x2="22" y2="25" />
  <line x1="23" y1="0" x2="23" y2="25" />
  <line x1="25" y1="0" x2="25" y2="25" />
  <line x1="26" y1="0" x2="26" y2="25" />
  <line x1="27" y1="0" x2="27" y2="25" />
  <line x1="28" y1="0" x2="28" y2="25" />
  <line x1="29" y1="0" x2="29" y2="25" style="stroke-width:2" />

  <!-- Colored Rectangle -->
  <polygon points="0.0,0.0 29.928824566042934,0.0 29.928824566042934,25.412616514582485 0.0,25.412616514582485" style="fill:#ECB172A0;stroke-width:0"/>

  <!-- Text -->
  <text x="14.964412" y="45.412617" font-size="1.0rem" font-weight="100" text-anchor="middle" >25</text>
  <text x="49.928825" y="12.706308" font-size="1.0rem" font-weight="100" text-anchor="middle" transform="rotate(0,49.928825,12.706308)">1</text>


  <!-- Horizontal lines -->
  <line x1="99" y1="0" x2="113" y2="14" style="stroke-width:2" />
  <line x1="99" y1="16" x2="113" y2="31" />
  <line x1="99" y1="33" x2="113" y2="48" />
  <line x1="99" y1="50" x2="113" y2="65" />
  <line x1="99" y1="57" x2="113" y2="72" style="stroke-width:2" />

  <!-- Vertical lines -->
  <line x1="99" y1="0" x2="99" y2="57" style="stroke-width:2" />
  <line x1="106" y1="7" x2="106" y2="64" />
  <line x1="113" y1="14" x2="113" y2="72" style="stroke-width:2" />

  <!-- Colored Rectangle -->
  <polygon points="99.0,0.0 113.9485979497544,14.948597949754403 113.9485979497544,72.25196873627125 99.0,57.30337078651685" style="fill:#ECB172A0;stroke-width:0"/>

  <!-- Horizontal lines -->
  <line x1="99" y1="0" x2="219" y2="0" style="stroke-width:2" />
  <line x1="106" y1="7" x2="226" y2="7" />
  <line x1="113" y1="14" x2="233" y2="14" style="stroke-width:2" />

  <!-- Vertical lines -->
  <line x1="99" y1="0" x2="113" y2="14" style="stroke-width:2" />
  <line x1="121" y1="0" x2="136" y2="14" />
  <line x1="143" y1="0" x2="158" y2="14" />
  <line x1="166" y1="0" x2="181" y2="14" />
  <line x1="188" y1="0" x2="203" y2="14" />
  <line x1="211" y1="0" x2="226" y2="14" />
  <line x1="219" y1="0" x2="233" y2="14" style="stroke-width:2" />

  <!-- Colored Rectangle -->
  <polygon points="99.0,0.0 219.0,0.0 233.9485979497544,14.948597949754403 113.9485979497544,14.948597949754403" style="fill:#ECB172A0;stroke-width:0"/>

  <!-- Horizontal lines -->
  <line x1="113" y1="14" x2="233" y2="14" style="stroke-width:2" />
  <line x1="113" y1="31" x2="233" y2="31" />
  <line x1="113" y1="48" x2="233" y2="48" />
  <line x1="113" y1="65" x2="233" y2="65" />
  <line x1="113" y1="72" x2="233" y2="72" style="stroke-width:2" />

  <!-- Vertical lines -->
  <line x1="113" y1="14" x2="113" y2="72" style="stroke-width:2" />
  <line x1="136" y1="14" x2="136" y2="72" />
  <line x1="158" y1="14" x2="158" y2="72" />
  <line x1="181" y1="14" x2="181" y2="72" />
  <line x1="203" y1="14" x2="203" y2="72" />
  <line x1="226" y1="14" x2="226" y2="72" />
  <line x1="233" y1="14" x2="233" y2="72" style="stroke-width:2" />

  <!-- Colored Rectangle -->
  <polygon points="113.9485979497544,14.948597949754403 233.9485979497544,14.948597949754403 233.9485979497544,72.25196873627125 113.9485979497544,72.25196873627125" style="fill:#ECB172A0;stroke-width:0"/>

  <!-- Text -->
  <text x="173.948598" y="92.251969" font-size="1.0rem" font-weight="100" text-anchor="middle" >1068</text>
  <text x="253.948598" y="43.600283" font-size="1.0rem" font-weight="100" text-anchor="middle" transform="rotate(-90,253.948598,43.600283)">510</text>
  <text x="96.474299" y="84.777670" font-size="1.0rem" font-weight="100" text-anchor="middle" transform="rotate(45,96.474299,84.777670)">2</text>
</svg>
</td>
</tr>
</table></div></li></ul></div></li><li class='xr-section-item'><input id='section-c407c865-2b27-48e1-91a3-5b1a1daaf565' class='xr-section-summary-in' type='checkbox' disabled ><label for='section-c407c865-2b27-48e1-91a3-5b1a1daaf565' class='xr-section-summary'  title='Expand/collapse section'>Attributes: <span>(0)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><dl class='xr-attrs'></dl></div></li></ul></div></div>


Now, it took a few seconds (or less) to execute the ```efold_xarray``` and create a new Dataset with the variable ```efold``` and a new dimension ```model```. From an user standpoint, the key concept of a ```dask.array``` is the notion of chunk. We can see the chunks as being subdataset with user-defined shape on which the unitary tasks will be applied.

Building upon Dask has several advantages. For instance, defining the chunks on which the computation will be performed is only modification needed in the code. The Dask library also allows for easily leveraging the resources of shared memory architectures (multi-core laptop or work-station) and resources of distributed memory architectures (clusters of cpu).

Yet, parallelization comes at a cost. Loading the data with  ```dask.arrays ``` is only done at the execution time if needed. This means that we have access to the Dataset without having to worry about the time it will take to load the data, but it will not simply reduce the time that it takes to load the data. The chunks also have implications on the performance of the code. If the chunks are too small, queueing up operations will be extremely slow, because Dask will translate each operation into a huge number of operations mapped across chunks. If the chunks are too big, some of the computation power may be wasted, because Dask only computes results one chunk at a time. 

<!-- # Parts -->

<!-- You can add parts to organize one or more book chapters together. Parts can be inserted at the top of an .Rmd file, before the first-level chapter heading in that same file.  -->

<!-- Add a numbered part: `# (PART) Act one {-}` (followed by `# A chapter`) -->

<!-- Add an unnumbered part: `# (PART\*) Act one {-}` (followed by `# A chapter`) -->

<!-- Add an appendix as a special kind of un-numbered part: `# (APPENDIX) Other stuff {-}` (followed by `# A chapter`). Chapters in an appendix are prepended with letters instead of numbers. -->



