# Key takeaways

This report presents some of the steps I took to create a function that calculates the lag-1 autocorrelation and e-folding time for a large dataset of downscaled climate data. Although this document is only a brief description of the challenges I encountered throughout the project, it throws some light on the difficult task of working with these data sets. Two points can summarize my experience beyond the realm of NumPy arrays. Firstly, the xarray library allows for a much more intuitive workflow.  This attribute is particularly important, as the multi-dimensional nature of xarray structures makes them particularly suitable for dealing with labelled scientific data stored in NetCDF files. Datasets also provide a solution for storing multiple variables sharing the same dimensions and coordinates. Secondly, the command ```xr.apply_ufunc``` allows for executing a function built on NumPy over a Dataset. This is an effective way of bridging the gap between NumPy and xarray, and has the advantage of creating new dimensions and variables along the way. However, the command also reveals the challenges of working with downscaled climate data that led me to explore the Dask arrays. These arrays allow for parallel computing, a considerable solution when working on local machines and servers with limited memory. Yet, the xarray and Dask libraries are relatively new compared with NumPy and some [developments](https://github.com/pydata/xarray/issues/585) are currently happening to fix issues with parallel computation. As climate scientists move forward with high-resolution climate data for local studies, improving the capacity to work multi-dimensional arrays is an essential step.
